### ISSUE TITLE
Java 7 - Symja library

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#17]
Hello, I removed all ``java 8`` source and replace with ``java 7``.
All test working perfect.
I created a pull request. Can you consider to merge this pull request?
I am plan to convert this project to ``Objective C`` by using ``J2ObjC`` 

As as mobile development, I use ``gradle`` build system instead of ``maven``. I remove all library except ``junit-4.6.jar`` and ``Lab4Math-2.0.5.jar`` and replace with java source (because ``J2ObjC`` can not convert binaries file and I cannot found source of ``Lab4Math-2.0.5.jar``)

**Comment by axkr** [comment]
Wouldn't it be easier to maintain the java7 version in a separate project?
This project can be stay with Java 8 and the new project I would try to also implement new features?

**Comment by tranleduy2000** [comment]
Yes, whenever you update a new feature you can create a pull request. Thank you very much.

**Comment by wanghao1992** [comment]
> Hello, I removed all `java 8` source and replace with `java 7`.
> All test working perfect.
> I created a pull request. Can you consider to merge this pull request?
> I am plan to convert this project to `Objective C` by using `J2ObjC`
> 
> As as mobile development, I use `gradle` build system instead of `maven`. I remove all library except `junit-4.6.jar` and `Lab4Math-2.0.5.jar` and replace with java source (because `J2ObjC` can not convert binaries file and I cannot found source of `Lab4Math-2.0.5.jar`)

Hi, I have some trouble while trying to import this as a module in my android project. The project keeps building without any error but repet log like this:

15:11:12.768 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
15:11:12.769 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
15:11:12.769 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
15:11:12.771 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
15:11:12.771 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
15:11:12.771 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
15:11:23.364 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running

After waiting for a long while, it comes out OutOfMemoryError and log is like this:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.StringCoding.encode(StringCoding.java:338)
        at java.lang.String.getBytes(String.java:918)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.gradle.cache.internal.filelock.LockFileAccess.<init>(LockFileAccess.java:31)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:136)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:86)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:73)
        at org.gradle.cache.internal.OnDemandFileAccess.readFile(OnDemandFileAccess.java:36)
        at org.gradle.cache.internal.SimpleStateCache.get(SimpleStateCache.java:47)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.get(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:31)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getAll(PersistentDaemonRegistry.java:69)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getDaemonsMatching(PersistentDaemonRegistry.java:111)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getIdle(PersistentDaemonRegistry.java:81)
        at org.gradle.launcher.daemon.server.CompatibleDaemonExpirationStrategy.checkExpiration(CompatibleDaemonExpirationStrategy.java:54)
        at org.gradle.launcher.daemon.server.expiry.AllDaemonExpirationStrategy.checkExpiration(AllDaemonExpirationStrategy.java:45)
        at org.gradle.launcher.daemon.server.expiry.AnyDaemonExpirationStrategy.checkExpiration(AnyDaemonExpirationStrategy.java:43)
        at org.gradle.launcher.daemon.server.MasterExpirationStrategy.checkExpiration(MasterExpirationStrategy.java:83)
        at org.gradle.launcher.daemon.server.Daemon$DaemonExpirationPeriodicCheck.run(Daemon.java:270)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
15:14:20.630 [ERROR] [system.err] Exception in thread "pool-2-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
15:14:20.631 [ERROR] [system.err]       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1855)
15:14:20.631 [ERROR] [system.err]       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2068)
15:14:27.041 [ERROR] [system.err]       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
15:14:27.042 [ERROR] [system.err]       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
15:14:27.042 [ERROR] [system.err]       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
15:14:27.043 [ERROR] [system.err]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
15:14:27.043 [ERROR] [system.err]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:14:27.043 [ERROR] [system.err]       at java.lang.Thread.run(Thread.java:748)
 
Have you had met this problem? Waiting for response. Thank you!

**Comment by axkr** [comment]
You should use the Java 7 fork from Duy Tran Le:
https://github.com/tranleduy2000/symja_android_library

**Comment by wanghao1992** [comment]
> You should use the Java 7 fork from Duy Tran Le:
> https://github.com/tranleduy2000/symja_android_library

Thank you for reply, I will have a try.
