### ISSUE TITLE
Fast Question:how to access the core parser,or those functions directly.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [axkr/symja_android_library#210]
**Is your feature request related to a problem? Please describe.**
Because i want to directly sent input to parser,no gui,no webinterface,nothing.
directly java.lang.string>parser
or
String>function>out

**Describe the solution you'd like**
A javadoc or simply direct me to the class or func responsible to parse string is probably enough.

If can somehow obtain a function core would be extremely awesome.I mean like,
solve(X^2+X+1),have output
cos(1),error,or no output,or return other stuff.
I doubt it can be as flexible as extracting a single function to test would be possible.But i have no idea

I know it is probably at core but...still quite big.Each java file is a thousand line,
There's like at least 100 files.so i have no idea.

*alternate*
add to project docs so future can also find this info and no need open issue ask again.

**Comment by axkr** [comment]
DId you try this: 
- https://github.com/axkr/symja_android_library/wiki/Java-usage

**Comment by xwaeaewcrhomesysplug** [comment]
Thx ,it work it is faster than most other small java math parser in github,but 1 digit slower then some,hybrid lang script engine eval.Keep up the good work,this will be one of my tools.Will report if found something wrong.

**Comment by xwaeaewcrhomesysplug** [comment]
Did some testing
![basictestjan17status](https://user-images.githubusercontent.com/67897598/104843716-69d6d300-590f-11eb-99c7-d7dba39b2d65.JPG)

Can you quickly go through what is the correct syntax.After this I think it should be ok to close this issue.Thank you very much.

**Comment by xwaeaewcrhomesysplug** [comment]
oh BTW,there's some error log.Luckily i use your gui to test.
>
Jan 17, 2021 9:56:11 PM org.matheclipse.io.servlet.AJAXQueryServlet evaluate
WARNING: (Xt-QlZfusOrwxgB8MppRa3GMYCu7KrXhFembSdDY) In::Integrate(Cos(x)^5, x)
java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
        at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:593)
        at org.matheclipse.core.eval.EvalEngine.stackPop(EvalEngine.java:2347)
        at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1479)
        at org.matheclipse.core.eval.EvalEngine.evaluateNull(EvalEngine.java:2058)
        at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:575)
        at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:895)
        at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1687)
        at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:1748)
        at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1417)
        at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:2072)
        at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:2000)
        at org.matheclipse.core.eval.ExprEvaluator.evalTryCatch(ExprEvaluator.java:364)
        at org.matheclipse.core.eval.ExprEvaluator.evalTopLevel(ExprEvaluator.java:342)
        at org.matheclipse.io.servlet.AJAXQueryServlet.evalTopLevel(AJAXQueryServlet.java:644)
        at org.matheclipse.io.servlet.AJAXQueryServlet.evaluateString(AJAXQueryServlet.java:469)
        at org.matheclipse.io.servlet.AJAXQueryServlet.evaluate(AJAXQueryServlet.java:419)
        at org.matheclipse.io.servlet.AJAXQueryServlet.doPost(AJAXQueryServlet.java:366)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by axkr** [comment]
Started updating the Wiki page for this issue:
- https://github.com/axkr/symja_android_library/wiki/Symja-browser-usage

**Comment by xwaeaewcrhomesysplug** [comment]
ah,very sorry but i tried some more equations but it does not seems to work.
>
solve({x==y,y=2},{x,y})
List: 2 is not a valid variable.
solve({x==y,y=2},x)
Solve: binary equation or inequation expression expected at position 2
solve({x==y,y==2},{x,y})
List: 2 is not a valid variable.
solve({x==y,y==2},{x})
Solve: binary equation or inequation expression expected at position 2
solve({x==y,y==2},{x>0})
List: x>0 is not a valid variable.
solve({x==y,y==2},{x})
Solve: binary equation or inequation expression expected at position 2
solve({x==y,y==2},{x,y})
List: 2 is not a valid variable.
solve({x==y,y>2},{x,y})
List: 2 is not a valid variable.

The last few test as you can see should be quite logical in a cartesian plane.
There should be a intersection point thus a solution.
I does not quite understand what is "List: 2 is not a valid variable.",as the list 2 is "supposed to put{x,y,z,other variable..}" right?

**Comment by xwaeaewcrhomesysplug** [comment]
Plan to move this to a new issue instead of this one lol.The parser itself should be fine.

**Comment by xwaeaewcrhomesysplug** [comment]
wait.
>
Clear(x,y)
solve({x==y,y==2},{x,y})

It works lol.sorry.awesome i will try print result.awesome work.
