### ISSUE TITLE
Calculate integrate of 2x always give stack size overflow on any Android device

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#32]
There are some lines of stack trace
```
 java.lang.StackOverflowError: stack size 1037KB
     at org.matheclipse.core.expression.AST1.isSameHead(AST1.java:265)
     at org.matheclipse.core.expression.AbstractAST.isAST(AbstractAST.java:1510)
     at org.matheclipse.core.expression.AbstractAST.isExcept(AbstractAST.java:1722)
     at org.matheclipse.core.patternmatching.PatternMatcher.matchExpr(PatternMatcher.java:861)
     at org.matheclipse.core.patternmatching.PatternMatcher$StackMatcher.matchRest(PatternMatcher.java:164)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher.matchOrderlessAST(PatternMatcher.java:101)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher$1.test(PatternMatcher.java:121)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher$1.test(PatternMatcher.java:105)
     at org.matheclipse.core.expression.AbstractAST.exists(AbstractAST.java:754)
     at org.matheclipse.core.interfaces.IASTImpl.exists(IASTImpl.java:156)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher.matchOrderlessAST(PatternMatcher.java:105)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher$1.test(PatternMatcher.java:121)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher$1.test(PatternMatcher.java:105)
     at org.matheclipse.core.expression.AbstractAST.exists(AbstractAST.java:754)
     at org.matheclipse.core.interfaces.IASTImpl.exists(IASTImpl.java:156)
     at org.matheclipse.core.patternmatching.PatternMatcher$OrderlessMatcher.matchOrderlessAST(PatternMatcher.java:105)
     at org.matheclipse.core.patternmatching.PatternMatcher.evalAST(PatternMatcher.java:466)
     at org.matheclipse.core.patternmatching.PatternMatcherAndEvaluator.eval(PatternMatcherAndEvaluator.java:222)
     at org.matheclipse.core.patternmatching.RulesData.evalDownRule(RulesData.java:586)
     at org.matheclipse.core.expression.Symbol.evalDownRule(Symbol.java:288)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:611)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evaluateNull(EvalEngine.java:1389)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:114)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:1406)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.reflection.system.Integrate.evaluate(Integrate.java:252)
     at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:624)
     at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:1103)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.eval.EvalEngine.evalAST(EvalEngine.java:496)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:946)
     at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:657)
     at org.matheclipse.core.reflection.system.Integrate.integrateByParts(Integrate.java:917)
     at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:1338)
     at org.matheclipse.core.expression.F.eval(F.java:3029)
```

**Comment by axkr** [comment]
I cannot reproduce bug with test `check("Integrate(2*x,x)", "x^2") `?

**Comment by tranleduy2000** [comment]
I think the stack size of JVM on Android device is small. 
But the method ``integrateByParts`` call very more times, could you improve it?

**Comment by tranleduy2000** [comment]
Awesome, thanks.
