### ISSUE TITLE
Symja 2.0.0 for Windows

### ISSUE THREAD

**Issue by ghost** [axkr/symja_android_library#505]
12 Mar 2022 you released Symja 2.0.0, but without all the necessary files (including the *bat files) to launch it in Windows as a web browser notebook. Why did you stop making releases for Windows?

**Comment by axkr** [comment]
I commited a configuration for the `appassembler-maven-plugin` Maven plugin which could be used to create the apps.

Assuming the command will be run from the parent `pom.xml` file location this command will create a distribution package for the web-interface and the command line apps:
```
mvn -pl matheclipse-io clean package appassembler:assemble
```

For Windows the following `*.bat` files will be generated:
`server.bat`, `mmaserver.bat`, `symja.bat` and `mma.bat`

The following command will create the JSON API server:
```
mvn -pl matheclipse-api clean package appassembler:assemble
```

For Windows a `symjaapi.bat` file will be generated.

**Comment by Ethereal-Fox** [comment]
@axkr I don't have Maven, Maven plugin etc. and I don't understand it at all 😕
I just want to know if you will release the **Symja 2.0.0** for Windows or not?

**Comment by axkr** [comment]
> I just want to know if you will release the **Symja 2.0.0** for Windows or not?

I added the release here:
- https://github.com/axkr/symja_android_library/releases/tag/v2.0.0-apps

**Comment by Ethereal-Fox** [comment]
> I added the release

@axkr thanks.

`symja.bat` and `mma.bat` are working correctly.

But I've problem with `server.bat` and `mmaserver.bat`

![Screenshot](https://user-images.githubusercontent.com/103583938/164531554-aeea2d49-d0d7-4893-a256-115db3909170.png)

**Comment by axkr** [comment]
Maybe the IP addrees or port is blocked by your windows security system?

Can you try to run it like this:
```
bin\server.bat -l -p 8080
```

**Comment by Ethereal-Fox** [comment]
@axkr  I tried but it didn't solve the problem. Also, I did not see any blocked ports and programs related to the Symja in the firewall list.

**Comment by axkr** [comment]
> @axkr I tried but it didn't solve the problem. Also, I did not see any blocked ports and programs related to the Symja in the firewall list.

I`ve no other idea? I use "Windows Powershell" and switch to the installation location in the Powershell command line and run the above command. The Powershell should show the logging of the inputs in the browser app.

**Comment by Ethereal-Fox** [comment]
@axkr here is the error message in cmd.exe console:

```
91239 WARN  [XNIO-1 task-1] org.matheclipse.io.servlet.AJAXQueryServlet - (TXvCqiVdvUSchJNjc7Pg9nPSyPxOStpX-kKuNXbM) In::2+2
91716 ERROR [XNIO-1 task-1] io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ POST /ajax/query/}
java.io.IOError: java.io.FileNotFoundException: Invalid file path
        at org.xnio.conduits.Conduits$1.run(Conduits.java:237) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        at org.xnio.conduits.Conduits$1.run(Conduits.java:227) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at org.xnio.conduits.Conduits.<clinit>(Conduits.java:227) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        at io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.writeFinal(AbstractFixedLengthStreamSinkConduit.java:175) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
        at org.xnio.conduits.ConduitStreamSinkChannel.writeFinal(ConduitStreamSinkChannel.java:104) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        at io.undertow.channels.DetachableStreamSinkChannel.writeFinal(DetachableStreamSinkChannel.java:195) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.server.HttpServerExchange$WriteDispatchChannel.writeFinal(HttpServerExchange.java:2171) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.ServletOutputStreamImpl.writeBufferBlocking(ServletOutputStreamImpl.java:582) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:619) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.ServletPrintWriter.close(ServletPrintWriter.java:117) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.ServletPrintWriterDelegate.close(ServletPrintWriterDelegate.java:81) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:492) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:587) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:334) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) ~[undertow-servlet-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Invalid file path
        at java.io.FileOutputStream.<init>(FileOutputStream.java:229) ~[?:?]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:123) ~[?:?]
        at org.xnio.conduits.Conduits$1.run(Conduits.java:232) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
        ... 30 more
```

**Comment by Ethereal-Fox** [comment]
cmd.exe also show the logging of the inputs

![Screenshot 2022-04-21 213609](https://user-images.githubusercontent.com/103583938/164539499-1e551114-6753-448f-8377-f49e66211448.png)

**Comment by axkr** [comment]
I guess it has something to do with the `new FileOutputStream("NUL:").getChannel()` which throws the `FileNotFoundException` and which is similar to the Linux `new FileOutputStream("dev/null").getChannel()`:

* https://stackoverflow.com/questions/25348997/nul-does-not-work-for-windows-but-null-does

**Comment by Ethereal-Fox** [comment]
@axkr I'm using the latest Oracle's [OpenJDK](https://openjdk.java.net/) 18.0.1

**Comment by masta99wrfvsHsa** [comment]
reference implemnetation jdk 17 worked fine.here.

**Comment by masta99wrfvsHsa** [comment]
oh wait you are using server. oops ignore my comment.

**Comment by HannesWell** [comment]
For me on Windows-10 using Java-11 GraalVM all four server scripts work fine.

**Comment by axkr** [comment]
This work around may also help?
* https://stackoverflow.com/a/72973272/24819
