### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$NonSerializableMemoizingSupplier does not implement the requested interface java.util.function.Supplier

### ISSUE THREAD

**Issue by js361014** [axkr/symja_android_library#797]
**Describe the bug**

```
java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$NonSerializableMemoizingSupplier does not implement the requested interface java.util.function.Supplier

	at org.matheclipse.core.reflection.system.Eliminate.zeroPlusMatcher(Eliminate.java:85)
	at org.matheclipse.core.reflection.system.Eliminate.extractVariableRecursive(Eliminate.java:386)
	at org.matheclipse.core.reflection.system.Eliminate.eliminateAnalyze(Eliminate.java:320)
	at org.matheclipse.core.reflection.system.Eliminate.eliminateOneVariable(Eliminate.java:660)
	at org.matheclipse.core.reflection.system.Eliminate.eliminateOneVariable(Eliminate.java:778)
	at org.matheclipse.core.reflection.system.Solve$SolveData.solveRecursive(Solve.java:1293)
	at org.matheclipse.core.reflection.system.Solve$SolveData.of(Solve.java:1782)
	at org.matheclipse.core.reflection.system.Solve.evaluate(Solve.java:1906)
	at org.matheclipse.core.eval.EvalEngine.evalASTBuiltinFunction(EvalEngine.java:1004)
	at org.matheclipse.core.eval.EvalEngine.evalRules(EvalEngine.java:2089)
	at org.matheclipse.core.expression.AbstractAST.lambda$evaluate$6(AbstractAST.java:2133)
	at org.matheclipse.core.expression.AbstractAST$NILPointer.orElseGet(AbstractAST.java:882)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:2133)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1763)
	at org.matheclipse.core.eval.EvalEngine.evaluateNIL(EvalEngine.java:2601)
	at org.matheclipse.core.eval.EvalEngine.evalQuietNIL(EvalEngine.java:2059)
	at org.matheclipse.core.builtin.Programming$Quiet.evaluate(Programming.java:2546)
	at org.matheclipse.core.eval.EvalEngine.evalLoop(EvalEngine.java:1737)
	at org.matheclipse.core.eval.EvalEngine.evalWithoutNumericReset(EvalEngine.java:2627)
	at org.matheclipse.core.eval.EvalEngine.evaluate(EvalEngine.java:2542)
	at org.matheclipse.core.expression.F.eval(F.java:3892)

```

**To Reproduce**

```
@Test
  public void test() {
    F.eval(F.Quiet(
            F.Solve(
                    F.List(
                            F.Equal(
                                    F.symjify("x")
                                    ,
                                    F.ZZ(1)),
                            F.Equal(
                                    F.symjify("x").plus(F.symjify("y").multiply(F.symjify("z")))
                                    ,
                                    F.ZZ(1))
                    ),
                    F.List(F.symjify("x"), F.symjify("y"), F.symjify("z")))
    ));
  }
```

**Comment by axkr** [comment]
Don't know if this is the reason, but I think I have to replace `com.google.common.base.Supplier` by  `java.util.function.Supplier`in the future.
https://github.com/google/guava/blob/9c3790f091dec76f62fe701a6568982c84c0ac70/android/guava/src/com/google/common/base/Supplier.java#L33

**Comment by js361014** [comment]
I added 
```
<dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>32.1.1-jre</version>
    </dependency>
```
and it solved issue.
