### ISSUE TITLE
test failure in testNDSolve

### ISSUE THREAD

**Issue by rebcabin** [axkr/symja_android_library#90]
# Submit a feature request or bug report

Replace any "X" with your information.

---

### Is this a request for a feature or a bug report?

bug report

### What is the current behavior?

```
junit.framework.ComparisonFailure: null  <Click to see difference>


	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.matheclipse.core.system.AbstractTestCase.check(AbstractTestCase.java:54)
	at org.matheclipse.core.system.AbstractTestCase.checkNumeric(AbstractTestCase.java:73)
	at org.matheclipse.core.system.LowercaseTestCase.testNDSolve(LowercaseTestCase.java:6532)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:91)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:159)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

### If this is a bug report, please provide steps to reproduce:

    mvn test

or 

    mvn clean install 

produces the following display

```
Results :

Failed tests:   testNDSolve(org.matheclipse.core.system.LowercaseTestCase): expected:<...4,0.1695491213425783[},(..)

Tests run: 1343, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] matheclipse ........................................ SUCCESS [  0.002 s]
[INFO] matheclipse-core ................................... FAILURE [ 53.329 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.430 s
[INFO] Finished at: 2018-10-06T16:33:07-07:00
[INFO] Final Memory: 23M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project matheclipse-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/matheclipse-core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :matheclipse-core
```

Or run unit test `testNDSolve` in IntelliJ to get stack trace above

```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/home/rebcabin/idea-IC-182.4505.22/lib/idea_rt.jar=32961:/home/rebcabin/idea-IC-182.4505.22/bin -Dfile.encoding=UTF-8 -classpath /home/rebcabin/idea-IC-182.4505.22/lib/idea_rt.jar:/home/rebcabin/idea-IC-182.4505.22/plugins/junit/lib/junit-rt.jar:/home/rebcabin/idea-IC-182.4505.22/plugins/junit/lib/junit5-rt.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/out/test/test:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/log4j-over-slf4j-1.7.25.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/log4j-api-2.5.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/jas-2.6.5938.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/junit-4.6.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/slf4j-android-1.7.25.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-fitting-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/jsr305.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/apfloat-1.8.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-optim-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-ode-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/log4j-core-2.5.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-core-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-stat-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/antlr4-runtime-4.7.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/commons-csv-1.4.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/logicng-1.4.0.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/txtmark-0.13.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/hipparchus-fft-1.3.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/lib/guava-26.0-android.jar:/home/rebcabin/Documents/GitHub/symja_android_library/symja_android_library/out/production/main com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit3 org.matheclipse.core.system.LowercaseTestCase,testNDSolve
```

### What is the expected or desired behavior?  

pass the tests

### Please provide use cases for changing the current behavior:

unknown

### Please describe your development environment (OS, browser, etc.):

Ubuntu 18.04, IntelliJ CE, Open JDK 10.1

```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
```

### Other relevant information:

X

**Comment by tranleduy2000** [comment]
It is not error, in some CPUs can give different floating point number.

**Comment by axkr** [comment]
Changed `checkNumeric` to `check` method to reduce precision for the test.

**Comment by rebcabin** [comment]
Thanks. Tests passed, change merged to our fork.
