### ISSUE TITLE
StackOverflowError occurs when computing `Simplify(Sin(Pi*Cosh(45522*Csc(17/36*Pi))))`

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#930]
There is the input
```
Simplify(Sin(Pi*Cosh(45522*Csc(17/36*Pi))))
```

<img width="657" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/45b61b0d-3ae3-45b3-a2c1-47abdfa82dfd">

```
java.lang.StackOverflowError
	at org.matheclipse.core.expression.F.ast(F.java:8625)
	at org.matheclipse.core.expression.F.PlusAlloc(F.java:14349)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:284)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
	at org.matheclipse.core.reflection.system.TrigExpand$TrigExpandFunction.expandCoshPlus(TrigExpand.java:292)
```

**Comment by axkr** [comment]
Best solution would be to implement these recursions in `TrigExpand` into an iterative loop.

"Work around" can be to set: `Config.MAX_AST_SIZE = 20000` to avoid to big expressions.

**Comment by axkr** [comment]
TODO replace recursive other versions in `TrigExpand#expandPlus()` with iterative verisions
