### ISSUE TITLE
StackOverflowError occurs when computing expr `Limit((-1+Sqrt(x))/Sqrt(-1+x), x -> Infinity)`

### ISSUE THREAD

**Issue by tranleduy2000** [axkr/symja_android_library#931]
There is the input
```
Limit((-1+Sqrt(x))/Sqrt(-1+x), x -> Infinity)
```

<img width="590" alt="image" src="https://github.com/axkr/symja_android_library/assets/19369448/37c59445-24cc-4fa9-979a-9171b47f4376">

```
java.lang.StackOverflowError
	at org.matheclipse.core.expression.AbstractAST.isAST(AbstractAST.java:3124)
	at org.matheclipse.core.expression.AbstractAST.isNumericArgument(AbstractAST.java:4085)
	at org.matheclipse.core.eval.EvalEngine.evalArgs(EvalEngine.java:795)
	at org.matheclipse.core.eval.EvalEngine.evalASTArg1(EvalEngine.java:921)
	at org.matheclipse.core.eval.EvalEngine.evalAttributes(EvalEngine.java:1275)
	at org.matheclipse.core.expression.AbstractAST.evaluate(AbstractAST.java:2172)
```

**Comment by tranleduy2000** [comment]
Another case that causes StackOverflowError: 
```
Limit((-1/E^x+E^x)/(E^x+E^(-x)),x -> Infinity)
```
